In [1]:
import sys
import sklearn
import numpy as np
import os
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt

In [4]:
np.random.seed(42)
m = 30
w1, w2 = 0.1, 0.3
noise = 0.1

angles = np.random.rand(m)*np.pi/2 -0.5
X = np.empty((m,3))
X[:, 0] = np.cos(angles) + np.sin(angles)/2 + noise*np.random.randn(m)/2
X[:, 1] = np.sin(angles) * 0.7 + noise * np.random.randn(m) / 2
X[:, 2] = X[:, 0] * w1 + X[:, 1] * w2 + noise * np.random.randn(m)

In [5]:
X_centered =  X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]

In [6]:
m, n = X.shape

S = np.zeros(X_centered.shape)
S[:n, :n] = np.diag(s)

In [7]:
np.allclose(X_centered, U.dot(S).dot(Vt))

True

In [8]:
W2 = Vt.T[:, :2]
X2D = X_centered.dot(W2)

In [9]:
X2D_using_svd = X2D

In [11]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X2D = pca.fit_transform(X)

In [12]:
X2D[:5]

array([[ 0.06117072, -0.06700474],
       [-0.47208699,  0.10778051],
       [-0.33998441,  0.01467248],
       [-0.29123923, -0.07169549],
       [ 0.36138409,  0.04774998]])

In [13]:
X2D_using_svd[:5]

array([[ 0.06117072, -0.06700474],
       [-0.47208699,  0.10778051],
       [-0.33998441,  0.01467248],
       [-0.29123923, -0.07169549],
       [ 0.36138409,  0.04774998]])

In [14]:
X3D_inv = pca.inverse_transform(X2D)

In [15]:
np.mean(np.sum(np.square(X3D_inv - X), axis=1))

0.006526192157717042

In [16]:
pca.explained_variance_ratio_

array([0.868802  , 0.07498183])